Repository importPI19fromDHGE/dhge-pi19-sem6, pull requests merged in 2022-02, with the labels that each got.

#4 Fehlende Links zu Modulen
  README.md
Labels: enhancement

#7 VL vom 07.02.2022 oder halt das was bei mir hängen geblieben ist
  .vscode/settings.json
  ISR-MUELLER/README.md
Labels: documentation

#9 IT-Recht 09.02.2022
  .vscode/settings.json
  ISR-MUELLER/README.md
Labels: documentation

#10 some minor changes to IT-Recht that were too late to the last PR
  ISR-MUELLER/README.md
Labels: do-not-merge, documentation

#8 Computer Forensik 09.02.22
  PRO-STRASS/README.md
  PRO-STRASS/assets/Rollen_CSN.png
Labels: documentation

#13 CB vom 10.02.2022
  CB-KUSCHE/README.md
Labels: documentation

#15 remove TODO, add Syntaxgraph
  CB-KUSCHE/README.md
  CB-KUSCHE/assets/syntaxgraph.png
Labels: documentation

#14 ISR-VL vom 11.02.2022
  .vscode/settings.json
  ISR-MUELLER/README.md
Labels: documentation

#16 Ergänzungen vom 14.02.2022
  .vscode/settings.json
  ISR-MUELLER/README.md
Labels: documentation

#18 Haupt-Editor für PRO hinzufügen
  PRO-STRASS/README.md
Labels: documentation

#19 ISR - Umstrukturierung und Ergänzung
  ISR-MUELLER/README.md
Labels: documentation

#17 IT-Recht 14.02.22
  .vscode/settings.json
  ISR-MUELLER/README.md
Labels: documentation

#21 ISR vom 16.02.2022
  .vscode/settings.json
  ISR-MUELLER/README.md
Labels: documentation

#26 Setup Anki Action
  .github/workflows/anki.yml
  .gitignore
  README.md
  anki.list
  pdf.list
Labels: documentation, enhancement
